### ISSUE TITLE
Clementine...

### ISSUE THREAD

**Issue by desputinski** [jonaski/strawberry#104]
Hi, I have another, more general question: 
why did you fork clementine - instead of becoming one of the Clementine-developers?

Best regards
desputin

**Comment by jonaski** [comment]
I guess the main reason was the lack of progress, the attitude towards audiophiles, few releases and clearly seeing that I wanted to go in a different direction. I also want to make more frequent stable releases.  I modified Clementine many years ago but never completed it, I also did a lot of porting to Qt 5 in 2013, but it was never completed and pretty broken. Although it compiled, it had tons of problems, my experience with Qt then was too weak back then, and it was too unfinished to contribute anything useful back. It also took to much time so I never bothered to finish it. I was actually using Amarok 1.4 years after clementine was released, and had to specialize lots of things to make it work on my distro.
When I saw all the complaints about Clementine with the removed alsa settings I thought I'd pick up some of the work I had already done years ago, since I saw that there were so many others that wanted the same. I had already added back the alsa device string setting, and in 2017 I started to work on it again, thats when I added the alsa device finder, I also contributed the device finder to clementine, but the settings there are much simpler because they do not want advanced settings.

**Comment by desputinski** [comment]
Hi jonaski,
thank you for the explanation! I hope, Strawberry will be a successful successor to clementine. I hate, if great software (like Amarok 1.4 way back then) get's lost... 
I know it's not a crucial feature, but one of the main reasons for me personally, why I'm using clementine (and before amarok 1.4) are the moodbars and the "intelligent Playlists". I had a feature request concerning the playlist-feature way back then (being able to combine AND and OR queries at the same time) but it was never implemented. So I hope, if Strawberry is faster in it's development features like this will get implemented....
best regards
desputin

**Comment by desputinski** [comment]
One last question: Why did you choose to fork an older version of clementine and not the 2016 Version?

**Comment by jonaski** [comment]
It's not an older version, not sure where you got that from. It was forked from the latest code on git at the time, but have merged since then.

**Comment by desputinski** [comment]
Ah, ok
