### ISSUE TITLE
"Transcode music" feature is not working

### ISSUE THREAD

**Issue by glaubersm** [jonaski/strawberry#123]
Hi

I use strawberry-full-git on Arch Linux running KDE Plasma 5.15.4, installed from AUR.

I tried to convert flac, mp3, wav, wma and ogg files to all audio format available,
strawberry always shows the error "1 failed" immediately after I click "Start transcoding" button.

**Comment by NucleaPeon** [comment]
What backend are you using?

**Comment by glaubersm** [comment]
VLC. Strawberry converts the files as expected when Gstreamer is used.

**Comment by jonaski** [comment]
Both the transcoder and the moodbar relies on gstreamer. The problem is that the gstreamer initialization is done in the engine class which isn't used unless gstreamer is selected, so I'll try to move the gstreamer initialization code earlier in the startup. If it doesn't work I will make the features disabled unless gstreamer is selected.

**Comment by jonaski** [comment]
You should now be able to use the transcoding independent of what engine is selected as long as it is compiled with gstreamer.
https://github.com/jonaski/strawberry/commit/3ed6817ac91813de3997e9075ab8418de17d3d2a
