### ISSUE TITLE
Scrobble to last.fm

### ISSUE THREAD

**Issue by hype3** [jonaski/strawberry#13]
Hi. Have been using Clementine for years and tested Strawberry but the only feature I want is missing and thats is to scrobble to last.fm

**Comment by rptx** [comment]
Hi,
I second this feature. :)
But don't implement it like Clementine using a token, (because the token is lost after a while, which lead to no scrobble)

**Comment by jonaski** [comment]
I'm not entirely against it as long as everything is invisible unless it's enabled in the configuration, and the default is off. Also, if it's going to be there, there should be an option to select which service to use and also include librefm. I belive there was a PR in Clementine for that, but it was rejected becaue they nedded to modify liblastfm and have it in 3rdparty, I don't mind that since liblastfm seems unmaintained at the moment anyway.
I currently don't use scrobbling myself, and right now there aren't any other contributors to this project, and I have to much to do already, so this will have to wait for now.

**Comment by jonaski** [comment]
I'm giving this a try, I've already been reading some of the API docs since I rewrote the last.fm cover provider using json without using the library. I will try writing it from scratch without using the lastfm library and using json instead of xml. Will try to implement both lastfm, librefm and listenbrainz.

**Comment by sanya567xxx** [comment]
I'm currently building 0.4.2 release from source under ubuntu. I have installed liblastfm 1.0.9 from here https://github.com/lastfm/liblastfm, from source too. Cmake in strawberry directory tells me it isn't installed. What am I missing?
Also building it from source failed with cmake being done but make returning this:
`[ 19%] Built target libstrawberry-common
ext/libstrawberry-tagreader/CMakeFiles/libstrawberry-tagreader.dir/build.make:61: *** target pattern contains no '%'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:629: ext/libstrawberry-tagreader/CMakeFiles/libstrawberry-tagreader.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`

**Comment by jonaski** [comment]
Code == Love :heart:
![love-code](https://user-images.githubusercontent.com/10343810/50375707-522ea280-0602-11e9-847a-95dd794187b5.png)

**Comment by alekksander** [comment]
also fuck=hug according to new Linus policy ;)

**Comment by jonaski** [comment]
Here is some info about the new scrobbler:

There is now support for both Last.fm, Libre.fm and Listenbrainz.
Last.fm and Libre.fm use the Scrobbling 2.0 API and share the same source code, the exception is the API URLs and that Libre.fm does single requests, while Last.fm uses multi-requests. They even share the API key and secret.
ListenBrainz has its own source code, and uses the ListenBrainz API, it also uses multi-requests.
All 3 can be configured in the settings, one or more, or all can be used at the same time.
Last.fm and Libre.fm uses a OAuth-like authentication where your web browser opens and you type your username and password in the web-browser. (This is the only authorized way for desktop applicatins). it redirects to a OAuth service that I host, which again redirects to localhost on a port where strawberry received the token which is used once to receive the session key. The session key is stored in the configuration, so you don't have to login again if you restart your computer or the player. The password is never shared outside of the scrobbler site.
ListenBrainz uses standardized OAuth authentication with a similar approach, except it redirects directly to localhost with a token which again requests an access token.
All scrobbles will be saved in a cache which will be loaded again if the player restarts, only deleted when they are successfully submitted to the server.
The cache is saved in a file in the standardized Qt 5 Cache Location: http://doc.qt.io/qt-5/qstandardpaths.html
On linux this is ~/.cache/strawberry
If you enable the scrobbler and the scrobbler service without being authenticated, they won't be sent to the server at all, and an annoying error will appear when you play songs.
There is an option to turn the scrobbler in an offline mode, this will prevent the error popup and trying to send anything to the server, it will only cache the scrobbles until you uncheck the offline mode.
Some useful debug output are logged to the console. Turning the scrobbler off won't cache anything or use the service at all.
There is a scrobble button in the main window (can be turned on in the configuration). If  you click it, you can enable/disable scrobbling. The icon is grey when the scrobbler is disabled.

**Comment by trougnouf** [comment]
Thank you! That's what I've been waiting for to try out Strawberry. So far it doesn't crash when playing ogg files which is what had been putting me off from Clementine, though I'm a bit confused by the apparent lack of dynamic playlist.

**Comment by jonaski** [comment]
@trougnouf I disliked the dynamic playlists feature thats why I didn't include it, guess we'll have other features to compensate.

**Comment by jonaski** [comment]
Scrobbling to 3 services at the same time right now (never used scrobbling before so I have no history except for testing previously):
https://www.last.fm/user/jonaskvinge
https://libre.fm/user/jonaski
https://listenbrainz.org/user/jonaskvinge

**Comment by jonaski** [comment]
Libre.fm and ListenBrainz works with Firefox, but Last.fm does not, all of them work with Chrome.

**Comment by alekksander** [comment]
last.fm works flawlessly so far, but haven't tested „offline” feature yet. i don't have listenbrainz nor libre.fm to try.

about dynamic playlists – is this the „50 never played”, „50 random tracks” playlists? i guess it's a nice feature letting one discover undiscovered content of the collection and although i've used it time to time i personally don't need it.

**Comment by alekksander** [comment]
well i praised the code too soon. it shows currently played track, but doesn't actually „scobble” it.
![image](https://user-images.githubusercontent.com/3148302/50401523-81264f00-078f-11e9-9737-a7bdcf76dd4a.png)

**Comment by jonaski** [comment]
That means that its sending now playing, not does not send scrobble.
Check the cache file if there are any songs in the cache.
Run strawberry from the a terminal window and see  if there is any useful output, ie errors returned by the server.

**Comment by alekksander** [comment]
i had a major system breakage. will setup everything back in a matter of days and report then.

**Comment by jonaski** [comment]
"Playing now" works now for ListenBrainz too. The problem was that I had to omit  "listened_at" (the timestamp).

**Comment by jonaski** [comment]
I've fixed the remaining stuff. It seems to work as expected but I'll leave this open for a few more days.

**Comment by alekksander** [comment]
still no luck scrobbling. it still sees what is being listen, but doesn't remember it. 

(do You plan a release? i'm not sure if i compiled right this time. for some reason it doesn't work with MPRIS2 and doesn't see gstreamer available when compiling)

**Comment by alekksander** [comment]
for me it's all working good now. thank You.

**Comment by trougnouf** [comment]
@alekksander @jonaski 

For me the dynamic playlist is mostly the ability to have playlist by rating (manual) and score (automatically generated by statistics), so that I can keep everything, listen to the ok stuff (~10000) most of the time, and to the great stuff (~3000) when I feel like it or I have guests over (s.t. it doesn't get repetitive), I can also set comments in the tags and use that in the playlist generator. All of this information is saved in the file metadata so it's never lost when my software changes.

These features with the fact that all this information is written in the file tags (s.t. it's technically portable) is why I've been using Amarok then Clementine this whole time. Unfortunately it's a deal breaker and I would have used anything else if it provided these features (since Clementine has had this really annoying tendency to crash when playing ogg files).

Thank you for your efforts, Strawberry looks like a great product and it seems not to have the crashing issue, unfortunately we don't have the same use cases and I understand you wouldn't want to work on a feature you dislike so it's not for me.

**Comment by Cogitri** [comment]
Sorry to nekrobump, but thanks @sanya567xxx  for writing about the protobuf thing, that helped me a lot! :)

**Comment by ayuinaba** [comment]
> the scrobbler works perfectly, BUT it still throws up authentication errors randomly, despite showing up perfectly on Last.fm

having this issue constantly lately :(
it throws a 201 forbidden error, which made me think might be related to me using a VPN, but i can access last.fm with no issue, so unsure if it really is due to that.
