### ISSUE TITLE
Icons and labels are not horizontally centered in the tab bar configured to "Small sidebar" mode

### ISSUE THREAD

**Issue by glaubersm** [jonaski/strawberry#135]
Hi

I use strawberry-full-git on Arch Linux running KDE Plasma 5.15.4, installed from AUR.
As we can see in attached screenshot, both labels and icons of the tabs are not horizontally centered when the tab bar is configured to "Small tabbar" mode. The icons also are lightly cut off.

![tabs](https://user-images.githubusercontent.com/15967631/56517677-ddb63280-6513-11e9-8be3-590288075018.png)

**Comment by jonaski** [comment]
It adapts to some qt5 style settings
Looks fine on my machine

![image](https://user-images.githubusercontent.com/10343810/56527205-95b40180-654d-11e9-9f46-3232d8a306a2.png)

**Comment by glaubersm** [comment]
Are you talking about widget style on KDE Plasma?
Tested breeze, fusion, kavantum and Qtcurve widget styles here and I always get the same result.
Could be something related to Qt version?
I noticed the bug while running Qt 5.12, 5.12.3, and 5.13 beta2.

**Comment by jonaski** [comment]
I dont think you can change every setting through KDE. But there is an utility called qt5ct and it changes some stylesettings. I know that it affects the tabbar.
It's not related to the Qt version, it's been like that in every single windows release since I adapted the fancy tabwidget that Vikram Ambrose wrote. I made a lot of changes to it though.
I've been debugging some other style related that I experienced on Fedora where the layout in the tabbar gets stretched from top to bottom, I was not able to figure anything in the code thay would do that, then I changed some settings in qt5ct and it suddenly worked.
I can look into this at some point again, there may be some workaround, but it's not a very high priority since it's a very minor issue.
If you want to debug it yourself you can try changing settings in qt5ct and see if it affects it, any input would be useful.

**Comment by glaubersm** [comment]
I have just tested qt5ct 0.38 on my system. The only styles available are breeze, fusion and windows
and none of them solves the issue reported here.
I will use an alternative side bar.
Thanks for your attention Jonas.

**Comment by jonaski** [comment]
I think I found a solution. https://github.com/jonaski/strawberry/commit/e0923a04940e04ea7af5985f08a0375e80ad5b85
Can you try the latest code now and see if it looks good now.

**Comment by glaubersm** [comment]
I just built strawberry-full-git on Arch Linux.
It's fixed!

**Comment by jonaski** [comment]
Nice, thanks for pointing out these things :thumbsup:
