### ISSUE TITLE
Freezing on song change (FLAC - different sample rate & bit depth)

### ISSUE THREAD

**Issue by dermamred** [jonaski/strawberry#164]
It happens that when the next song has a different sample rate (...maybe it's also caused by different bit depth)... when program freezing I have to force exit and even so I have to kill the process 'cos there are several "strawberry-tagreader" instances... maybe this issue is related to this one... https://github.com/jonaski/strawberry/issues/106#issue-430026589 ...I'm using Mint 18, streaming to USB DAC → Gstreamer → alsa → plughw → no volume control & everything on backend pane set to off.

**Comment by jonaski** [comment]
Fixed https://github.com/jonaski/strawberry/commit/e5f312356798629aee778969d1f1774483cfd240
There was a block in ErrorMessageReceived() on gst_pad_send_event() that was causing freeze instead of showing the error.
If you get the "Could not get/set settings from/on resource" when switching between sample rates, it's related to the system setup.

**Comment by dermamred** [comment]
I get the message U wrote, "Could not get/set settings from/on resource", w/ same setting as I described in the first comment... U tell that's related to system setup, so what can be done to avoid this message and to press play, more than once, to restart playing tracks w/ different bitrate/samplerate?... 'cos as it is now, it's an half-baked solution... program doesn't freeze but also doesn't go on playing next track displaying the popup... so U now have to close the popup, press play more than once or clicking on track, again more than once, and then U can listen the following track... it's easy to imagine what this means if U have a playlist where there are mixed tracks w/ different bit-samplerate... e.g., 2 track 16/44100 then 3 track 24/192 then again 24/88200... it's a PITA, almost unusable.

**Comment by jonaski** [comment]
It only happens with gstreamer and Audacious does not use gstreamer.
I got the problem on one of my computers too, that's how I was able to fix the freeze bug so fast.
it occurs when playing after being idle for a while, and it also happens when I set a alsa device and try to play a track with a different sample rate than the previous.
I have tested the same DAC on another linux computer where it works fine. So it's not related to the specific DAC either.
I can't find any differences in the alsa configuration, the main difference is that the one that isn't working is opensuse tumbleweed and the one working is opensuse leap 15.1, but I run a custom low-latency kernel on the one that is working that was not upgraded for a few years. I will try to build a new custom kernel that matches on both and see if there is a change.

**Comment by dermamred** [comment]
Thanx.


(Meanwhile I'll try to see what happens choosing others engine and not alsa, even if I think these 2 are the most used, and by default, by users/distro... so it could be good if this combination would work... I chose Strawberry 'cos I was searching a player that was easy to set for a bit-perfect listening... this means I mostly listen to FLAC and using a capable USB DAC I have files w/ different bit-samplerate... who plays MP3 doesn't have this problem... but there are several players that are able to manage a big MP3 library.)
