### ISSUE TITLE
Better lyrics handling

### ISSUE THREAD

**Issue by supertin** [jonaski/strawberry#174]
Short version:
Is it possible to have a feature added to adjust how Strawberry goes about querying for lyrics (like tweaks to odd punctuation, spelling or remix attributions sometimes present in song titles)?
Or to give the user a per-song search option that could even allow lyrics to be unrelated to the actual file tags?

Longer version:
I just turned on lyrics for some Christian dance remixes. Several songs come up with no lyrics due to simply having no match (which is OK as an initial outcome). Several have come up with completely unrelated lyrics. Only one so far has actually correctly matched (technically an original track, not a remix).

Where it gets odd is that if I take the artist and title, or just the song title, and feed it to audd (eg https://api.audd.io/findLyrics/?q=Your%20Love%20Never%20Fails%20(oh%20snap%20it%27s%20luke!%20remix)), I get the correct results. I've tried several combinations, and have not seen the lyrics I'm presented with.
Another case that's just come up - "Hillsong - One Thing (Ruebs Remix)" returns the lyrics for a different, very old, Hillsong title (All Things Are Possible). Audd seems to provide zero results for the actual artist title combination as the track is currently tagged.

I'm left wondering what tags I should even edit to make it match right, since some already have what seems to be the correct tags. If we had a simple little search box specific to lyrics, that could override the default query for that track, many times a user could simply point to the right lyrics.

**Comment by jonaski** [comment]
When I first added lyrics from AudD it was returning a lot of garbage results, I noticed that when searching it was not only searching the song artist and title, but if something from the title was was matching in an actual song lyric it returned garbage results where the "lyrics" were thousands of characters long, I sent them an email and informed them, but they just denied it. So I added some special checks to filter out garbage results, it discards any results that are over 6000 characters long, and it discards results where both the returned artist and song title do not match the searched artist & song.
I found that for the songs in my collection it either returns correct lyrics or no results, and the amount of songs it returns lyrics for is quite impressive.
I also think AudD has improved their service too, because when testing now it does not return garbage results for some song where it used to.
But recently I added support for Chart Lyrics too, so maybe it is using that one instead.
I added a text on the bottom now that will show which provider it uses the lyrics from, so it will be easier figure it out.
I also added a check to discard results from ChartLyrics if both artist and title don't match.
It's not likely that they have lyrics for more obscure stuff, but it should not use bogus or incorrect results anyway.
