### ISSUE TITLE
Adplug support

### ISSUE THREAD

**Issue by jcelerier** [jonaski/strawberry#19]
Hello,
I would be interested in adding support for playback of impulse tracker music formats (old video game music) with Adplug : https://github.com/adplug/adplug

where should I look into the code to be able to do this ? Thanks !

**Comment by jonaski** [comment]
Do these have metadata? If they do, it should be added to support them in taglib first.
If they don't it won't make much sense scanning them, but you can add the extensions to be accepted in Song::InitFromFilePartial in song.cpp, you can then add them to the playlist either by dragging the files or doing music / open file, you will then be able to see if they play with gstreamer, I know it plays sega and nintendo music VGM and SPC.
It would make more sense to use a gstreamer plugin, for example this:
https://github.com/dv1/gst-nonstream-audio
Otherwise you'll need to write the engine code, you can look at phononengine.cpp for example and add Adplug as a engine.

**Comment by jcelerier** [comment]
> Do these have metadata? If they do, it should be added to support them in taglib first.

Some, e.g. generally at least author and track name. Going to try to add them as you said and see what happens.

**Comment by jcelerier** [comment]
hmm, that's weird: at least MOD, XM, IT are here in TagLib::FileRef yet they don't appear in the file browser pane.

**Comment by jonaski** [comment]
Maybe just the file extension filtering?
They may need to be added here:
https://github.com/jonaski/strawberry/blob/master/src/widgets/fileview.cpp#L50

**Comment by jonaski** [comment]
To appear in the collection they need to be added here to actually read the tags:
https://github.com/jonaski/strawberry/blob/master/ext/libstrawberry-tagreader/tagreader.cpp#L142
