### ISSUE TITLE
Ratings

### ISSUE THREAD

**Issue by cup** [jonaski/strawberry#20]
Nice program, but I see no way to view or set ratings

**Comment by jonaski** [comment]
If you want ratings use Clementine.
This a place to report problems not feature requests.

**Comment by desputinski** [comment]
I'm also using ratings in clementine. It's a very time consuming process to rate a whole music collection... If people see Strawberry as some kind of successor to Clementine, I think the question is legit :) But I can understand that more basic features come first...

PS Where is the appropriate place for feature requests?

**Comment by jonaski** [comment]
Yes, I think I have to consider bringing the ratings and the smart playlists back, that's the two things that some users miss. I don't really want feature requests on github, because leaving them open just creates false impressions that it will be done, and there are just way too many things people want, we would never have time to do everything.
I didn't really consider this project as a successor or replacement to Clementine, just an alternative, but it seems that progress on Clementine have more or less stalled completely so I see that it's more relevant now.
As for feature requests I plan to create a forum or malinglist where it can be discussed, but haven't really decided what exactly we want yet. GitHub is really bad for technical support, because mostly developers answer questions, mailing list or forums work much better for that where regular users can help each other.

**Comment by desputinski** [comment]
All right, thanks for the explanation!
I would offer help in regard to web formum, website and so on. I'm pretty good with wordpress and ok with other CMSes... I could also create a mailing list via my webspace provider, which is an open source, free software, quite political provider based in Berlin (in-Berlin)...

**Comment by DanAlexson90** [comment]
> As for feature requests I plan to create a forum or malinglist where it can be discussed, but haven't really decided what exactly we want yet. GitHub is really bad for technical support, because mostly developers answer questions, mailing list or forums work much better for that where regular users can help each other.

Nowadays, _Discourse_ is a good platform for that:

https://www.discourse.org/
