### ISSUE TITLE
Linux: Disconnect from sound service on pause?

### ISSUE THREAD

**Issue by archfrog** [jonaski/strawberry#234]
Hi,

I'm using Strawberry on Ubuntu Desktop 19.04 x64 and it works great.  

One problem I have, though, is that if I get an incoming Skype call, pause the music, and try to answer my Skype call, I get no sound whatsoever.  This despite running Skype and Strawberry on two different sound cards (Strawberry is connected to an Audio gd DAC and Skype to the onboard audio).

I never had this problem with Foobar2000 on Windows, so I **guess** it is because Strawberry does not release the audio resources when you pause playback.  Foobar2000, on the other hand, does release everything on pause so that there are no interferences with other software in the system - you can even play games while Foobar2000 is on pause.

So I'd like to suggest that you sort of "hang up everything" on pause and then reconnect on resumed playback.

**Comment by alekksander** [comment]
afaik this is how alsa works – it's rather holding the stream on pause than releasing it. it is something that has been bothering me too, but i think You can get used to it. still – would be excellent to have pause that stops the stream and remembers audio position to start with on unpause.

**Comment by jonaski** [comment]
He doesn't mention he's just alsa directly, and ubuntu has pulseaudio by default so unless he disabled it, or uninstalled it, I'm assuming he's using puseaudio. But even with alsa, I don't think it should block when it's on 2 separate soundcards.
But when testing here, both with or without pulseaudio I'm not having an issue. When testing alsa I stopped/disabled pulseaudio, reopened skype.
I'm using the test call function in Skype, it plays sound there to my headset while strawberry is set on pause with output to the DAC.
This issue is most likely a system setup issue, but a workaround could be to use the resume playback option and just close strawberry when you receive a call, then open it again afterwards.

**Comment by archfrog** [comment]
I am using Alsa.  I'll try Pulseaudio and see if it works with my DAC.

**Comment by archfrog** [comment]
Just to finish this ticket up, in case others stumble across it.

I switched to Pulseaudio, made a test call with Skype, and Strawberry was automatically silenced during the test call, and automatically resumed playback once I ended the test call.  

I only used ALSA out of ignorance :-)  Never really grokked the 117 Linux sound subsystems.
