### ISSUE TITLE
General Question: Sound quality?

### ISSUE THREAD

**Issue by desputinski** [jonaski/strawberry#251]
Hi, I have a general question concerning the sound quality of strawberry in comparison to Clemeintine, as this was one of the reasons for the fork...

I have a musica fidelity V90 DAC and my music files are normal FLAC files ripped from audio cds.
So is the sound quality out of the box better with strawberry, or only if I have higher res audio files (48k)?
And which audio settings in the "Backend" are the best? Pulse or ALSA or OSS?

best regards
desputin

**Comment by jonaski** [comment]
The main difference is that you can play directly to ALSA without re-sampling. Which in my opinion will get the best sound to a DAC. In Clementine both the equalizer and analyzer is causing re-sampling, that's the main issue I guess.
I've seen some threads where it's discussed where users claim that the sound quality is better in Strawberry, and I've also received a lot of e-mails directly from users where they claim it sounds better. And many of these users have hi-end equipment and good DAC's.
I think also it makes a difference with CD quality albums (44.1/16) when selecting a ALSA device since they then aren't re-sampled to 48k and 16 bits.
As for the settings, ALSA, PulseAudio and OSS. Oss isn't really relevant anymore, but is just there for convenience (it's the old sound system in Linux before ALSA).
As for ALSA vs PulseAudio, I can only speak for me, but I've used Linux since long before PulseAudio existed and was available in any Linux distros, I've used Linux since the late 1990's, and permanently for desktop since 2004 without any Windows/Apple computer in the house. (having Windows or Apple in the house is like having rats in your house and not doing anything about it, but that's a different topic). But now I have a laptop with dual boot with Windows, but I only use windows for testing the strawberry releases. So I've never used Windows as music player or media center. I was playing music mainly from CD's before I ripped all my music to FLAC and used Amarok for playing them back then.
I was also using MythTV for many years both with cable TV and then later satellite. When PulseAudio became default enabled in distros, I ran into all sorts of problems with my setup, latency probably being one of the main issues. So I've always uninstalled pulseaudio from all my systems. I never liked PulseAudio to be honest, I got too much negative history with it.
The need for pulseaudio is when if you have multiple input / output sources and need a way to configure it. If you use ALSA only, but have different soundcards (or headphones) you run into problems with some applications, like web browsers for example, because you can't select what output device it uses.
But if you use a computer for music only, or movies, and you need only 1 ontput device (like a DAC) you can disable/uninstall PulseAudio and use only ALSA to get the best sound to the DAC. I think it's pretty pointless to use PulseAudio when you use a computer in the living room for music, where you don't have the need for other sound outputs/inputs.
But if you have a workstation, where you listen to music, but also need to make phone/video calls over the internet (or something else), you sometimes need PulseAudio to handle it.
I don't think it's a good idea to use ALSA directly if you have PulseAudio enabled on the computer as well (but it seem to work too).
As for me now, I don't have PulseAudio installed on the computer in my living room that I use only to play music and watch movies, I have disabled all other sound cards in the BIOS and through modprobe. That way I don't have any problems outputting the sound to the correct device in the web browser when I watch a movie or youtube. But I still set the ALSA device in Strawberry to prevent re-sampling.
On the "work" computer in my home office, I also have a DAC, but I got PulseAudio installed now, but I just enable it when I need it, then disable it. I need it sometimes if I do a web call, but that really depends if the application, even Skype supports ALSA, but things like Google hangout does not, so then you need PulseAudio.
My conclusion is that it's probably a good idea to disable or uninstall PulseAudio if you use the computer to a Hi-Fi stereo and want the best possible sound, but the easiest route for a computer that you use for different purposes to just use PulseAudio. (and you can still output strawberry to ALSA when you don't use sounds in other applications, I guess).

**Comment by desputinski** [comment]
Hi jonaski,
thank you for this detailed explanation. For me it is more convenient, to keep pulseaudio. But I just tested Strawberry with alsa in Comparision to Clementine. Indeed the sound quality is better!
Great!
