### ISSUE TITLE
Ampache compatibility

### ISSUE THREAD

**Issue by goliashcz** [jonaski/strawberry#255]
Firstly thank you for you work.

Would it be possible to support older version of Subsonic API? Or make it configurable. Or if you could work with Ampache developers (https://github.com/ampache/ampache/pull/1965#issuecomment-525199322) to get Strawberry to Ampache connections working. Currently it doesn't work because of 1.13 vs. 1.15 incompatibility.

**Is your feature request related to a problem? Please describe.**
Ampache currently supports Subsonic API 1.13.

**Describe the solution you'd like**
Either Ampache API to enhance to 1.15 or Strawberry to 1.13.

**Describe alternatives you've considered**
I use DSub Android music player to listen my music from Ampache but I would welcome a possibility to connect from my Linux laptop. Amarok is deprecated and I like Strawberry as modern Qt5 app.

**Comment by jonaski** [comment]
I've set the API version to 1.13.0 now so you can try the development builds and see if it works with ampache.

**Comment by lachlan-00** [comment]
Let me know what you need and what breaks.

I only went to 1.13 as it was the minimum required for token-based auth.

**Comment by goliashcz** [comment]
In settings Test connection is successful but in Subsonic tab I am getting 
Error transferring https://192.168.123.172/ampache/rest/getAlbumList2?type=alphabeticalByName&c=Strawberry&v=1.13.0&f=json&u=goliash&p=enc%3A6b6c6f62617361 - server replied: Not Found (203)

I've used this build: strawberry_0.6.3-45-g9b45f06_amd64.deb 

This is from my web server log. IMO the problem is that you use GET instead of POST.
<pre>192.168.123.110 - - [28/Aug/2019:08:41:00 +0200] "GET /ampache/rest/getAlbumList2?type=alphabeticalByName&c=Strawberry&v=1.13.0&f=json&u=goliash&p=enc%3A6b6c6f62617361 HTTP/1.1" 404 3750 "-" "Mozilla/5.0"

192.168.123.193 - - [28/Aug/2019:08:41:32 +0200] "POST /ampache/rest/getAlbumList2.view?u=goliash&p=enc:6b6c6f62617361&v=1.2.0&c=DSub&type=alphabeticalByName&size=20&offset=0 HTTP/1.1" 200 4578 "-" "DSub"
</pre>

**Comment by lachlan-00** [comment]
That's a method from 1.14 so it won't be available in Ampache yet

```
getAlbumInfo (Since 1.14.0)
getAlbumInfo2 (Since 1.14.0)
getCaptions (Since 1.14.0)
getVideoInfo (Since 1.14.0)
getScanStatus (Since 1.15.0)
startScan (Since 1.15.0)
```

**Comment by lachlan-00** [comment]
I'm sorry that is in the API.

**Comment by jonaski** [comment]
GET is working fine for Subsonic and Airsonic, I don't see anything in the Subsonic API documentation about using POST. Also, POST is usually used to submit data to the server for storing, and not normally for just getting something.

**Comment by jonaski** [comment]
@lachlan-00 Do I need to use POST for amapache, does it need ".view" at the end of getAlbumList2, or is it a bug in amapache?

**Comment by lachlan-00** [comment]
the *.view comes in on all my subsonic urls so i'm guessing that's part of the subsonic api. it's not something ampache specific that i'm aware of.
```
https://music.org/rest/getBookmarks.view?u=username&p=enc:35sdfsfsdfds784c52&v=1.2.0&c=DSub
```
When i remove the .view portion i get a 404

**Comment by jonaski** [comment]
I think that's the problem, looks like I'm using .view for ping, but not the other requests.

**Comment by jonaski** [comment]
I had to install ampache myself to fix this.
The problem was indeed the missing ".view". When I wrote the Subsonic implementation I looked at the documentation on http://www.subsonic.org/pages/api.jsp
I don't see it mentioning ".view" for anything other than ping, and it worked fine without ".view" for both subsonic and airsonic. This could probably be worked around for ampache by editing the htaccess files, but I've added ".view" now anyway since I see other clients doing it, and it doesn't break airsonic.

However I found a different problem that I also had to workaround. ampache isn't following the API correctly in regard to the Json data types for id, albumId, artistId, etc. According to the documentation it should return string, i.e. "id":"53" but ampache is returning integers, like "id":200000065

I also had to set the API version down to 11. But I probably set the API version much too high in the  beginning because I wasn't sure about it.

See:
https://github.com/jonaski/strawberry/commit/c0ebbc8e2f525b7098feac5a46ca47ec6e12f513

Let me know if it works for you now when the builds finishes.

**Comment by lachlan-00** [comment]
thanks for spotting that!
I'll change those int's to strings asap.

The API in ampache has the minimum support for 1.13 but supports all version below that without issue. the big difference between 11 and 13 is the token auth.

Ampache will only support token auth using an API Key as the password implementations between subsonic and ampache are too different to easily join.

**Comment by goliashcz** [comment]
Yes, it works! Thank you. (using 0.6.3-60-gc5b78dd build)
