### ISSUE TITLE
Pretty OSD wrong position with dual monitor

### ISSUE THREAD

**Issue by Superpiffer** [jonaski/strawberry#269]
I'm trying to position the OSD on the secondary screen on Windows 10, I have on the right the primary screen and on the left the secondary screen. The problem is that the window doesn't stick to the secondary screen and shows up on the primary screen no matter what. 
I checked the settings with Regedit and if I change screen I can see the "popup_screen" parameter switch from "\\.\DISPLAY2" to "\\.\DISPLAY3", the "popup_pos" parameter remain the same: "@Point(-1 -1)" (Bottom Right corner).
The effect is that the OSD shows up on the bottom left side of the primary screen instead of the bottom right side of the secondary screen.

**Comment by jonaski** [comment]
It works fine on Linux with Qt 5.13.1 (latest), same version I ship with the windows installer.
The position probably works different on Windows, I have to admit I never tested it on Windows after I switched QDesktopWidget to QScreen.
I can see if I can hook up a Windows laptop to my screens here.

**Comment by jonaski** [comment]
I tested on Windows 10 now, works fine for me.
I have 2 Eizo FlexScan EV2450 monitors with 1920 x 1080.
What version are you using?
Do you have 2 monitors with the same resolution or different?

**Comment by Superpiffer** [comment]
I have, at work, two identical Samsung SyncMaster S24 with the same resolution (1920x1080). Anyway I tried to make the left display as primary and the right display as secondary and the OSD works properly on both screens. Apparently I have this problem only if the secondary display is on the left, maybe due to negative coordinate from primary? I don't know how to debug it...

**Comment by jonaski** [comment]
Yes, your right, on Windows there is negative numbers for the geometry
I can reproduce the problem like you said when setting the right monitor as the primary.
The problem is that the qBound that is done before move() does not handle negative numbers. Removing the qBound fixes it halfway, but it won't be prefect since it won't take the size of widget into consideration so the OSD widget can be bit off screen after placement. The relevant code is here:
https://github.com/jonaski/strawberry/blob/master/src/widgets/osdpretty.cpp#L396
I will try workout a better fix when I get some more time.

**Comment by jonaski** [comment]
There were actully two different bugs in OSD Pretty, that's what got me confused in the first place.
I had a check for no position set `popup_pos_.isNull()`, that was actually returning true when the position was upper left corner QRect(0,0), that's what confused me. Both problems fixed now.
