### ISSUE TITLE
Send track artist to listenbrainz

### ISSUE THREAD

**Issue by guedressel** [jonaski/strawberry#273]
**Describe the bug**
In listenbrainz I find the "Album artist" information tracked, tracking the "Artist" information might improve accuracy for listenbrainz. On libre.fm "Artist" gets already tracked instead of "Album Artist".  
Example: Album artist: "Various Artists", (Track) Artist: "Susanne Blech"

**To Reproduce**
Activate listenbrainz tracking. Play a track with different information in "Album Artist" and "Artist" meta tags. Check listenbrainz logs.

**Expected behavior**
Having "Susanne Blech" tracked, instead of "Various Artists".

**System Information:**
 - Arch
 - Strawberry 0.6.3

**Additional context**
I'm enjoying strawberry a lot! Thank you.

**Comment by jonaski** [comment]
Last.fm and libre.fm has it's own parameter for album artist that is sent if album artist is set for the song.
But listenbrainz only have "artist_name", I think the most accurate to send in that case is album artist, since that's what identifies what release it is that is sent in the other parameter "release_name".
But I made an exception, if album artist is set to "various artists" case-insensitive it will use the artist instead.

**Comment by guedressel** [comment]
Thanks! That was a quick fix.

Just began to look into the listenbrainz API myself:
https://listenbrainz.readthedocs.io/en/production/dev/json.html#json-doc

Do you check for *_mbid musicbrainz metatags?
In my collection I have a lot of musicbrainz tags - therefore listenbrainz would easily pick up the recording / release information if strawberry would submit those too.

What do you think about integrating musicbrainz specific tags to the listenbrainz submissions?

**Comment by jonaski** [comment]
It can be done, but it involves a lot more work. We have to create fingerprints for each song then. The best way to do it I think is to calculate the fingerprint at the same time as scanning the collection, then store it in the DB. Then we can simply request the mbid from acoustid.org (we already do that when requesting tags from musicbrainz) before scrobbling a song.

**Comment by guedressel** [comment]
What if a track *already contains* such musicbrainz tags - do you really need to (re-)calculate the musicbrainz fingerprints?

**Comment by jonaski** [comment]
No, but I'm not sure how to read mbid from tags, is it a known tag both in Vorbis comments and ID3v2, does all audio formats support it?

**Comment by jonaski** [comment]
Looks like there is some info here https://picard.musicbrainz.org/docs/mappings/

**Comment by guedressel** [comment]
These are the tags I found in [Picard](https://picard.musicbrainz.org/).  
(Tested with .mp3 and .flac)

```
musicbrainz_albumartistid
musicbrainz_albumid
musicbrainz_artistid
musicbrainz_discid
musicbrainz_originalalbumid
musicbrainz_originalartistid
musicbrainz_recordingid
musicbrainz_releasegroupid
musicbrainz_trackid
musicbrainz_workid
muiscip_fingerprint
musicip_puid
```

**Comment by BrandonKMLee** [comment]
Question: is it possible to create a moodbar-like feature for MusicBrainz acousticid hashing?

**Comment by pasdechance** [comment]
Just a quick question, as I am having the same issue now. My music is tagged with beets / musicbrainz and is submitting album artist instead of artist, which is a pain because tagging something as "various artists" when the album in question is a soundtrack or something like [“fabric presents Leon Vynehall” by Leon Vynehall](https://musicbrainz.org/release/99713901-1445-4028-9e59-6eea35b8debe).

Is there an easy fix that I could do on my own to get it to submit the track artist instead? Forgive me if the answer is posted above, I've read through but I don't see if there is something I can do myself.

**Comment by jonaski** [comment]
This is now done, for more information see my post on https://forum.strawberrymusicplayer.org/topic/199/send-musicbrainz-ids-in-listenbrainz-submissions/8

**Comment by BrandonKMLee** [comment]
Nice to see this being made. Also would be sweet to get it downloaded and used https://github.com/chocolatey-community/chocolatey-package-requests/issues/739
