### ISSUE TITLE
Strawberry stops session logout

### ISSUE THREAD

**Issue by Fenix1782** [jonaski/strawberry#277]
Having Strawberry opened (playing anything or not makes no difference) stops session logout.

**To Reproduce**
Just keep Strawberry opened and try to logout/reboot/shut down

**Expected behavior**
Like any other program it shouldn't prevent system logout

**System Information:**
System: Kernel: 5.2.20-1-MANJARO x86_64 bits: 64 compiler: gcc v: 9.2.0 Desktop: KDE Plasma 5.16.5
Strawberry: version 0.6.5 

**Additional context**
Message i get:"Logout cancelled by «/usr/bin/strawberry" 
Strawberry closes but i need to redo the logout again.
Note #1: this is a fresh O.S. installation, made 3 days ago. The strange thing is that previously i still had Manjaro KDE (installed 2 years ago, and always been updated) and no problem came from Strawbarry
Note #2 (maybe not related & unuseful): there is no way to make Strawberry to remember the width of the side panel (the one which displays folders, album pic, devices, etc)

Sorry for my english

**Comment by RomanHargrave** [comment]
I have experienced this as well. Strawberry cancels the initial attempt to log out/hibernate/shut down, and then exits.

**Comment by lukester1975** [comment]
Hi, I'm not sure the fix is working correctly in KDE (haven't tried it elsewhere).

If `keeprunning` is set, on logout the close event is still ignored (blocking the logout) but the application will minimize itself to the tray.

Logging out a second time appears to work, it just takes a while.

Simple fix for me is just to turn off `keeprunning`, but maybe there's a proper solution (a way to distinguish between a window close and user logout close event maybe? I don't know QT I'm afraid!).

Thanks for the good work keeping the Amarok 1.4 style alive!

**Comment by alekksander** [comment]
unfortunately not fixed for me

**Comment by jonaski** [comment]
If "keeprunning" is set, then it will minimize to tray instead of quitting, thus prevent any logout, so you need to turn that off, or minimize or close Strawberry before you logout.

**Comment by jonaski** [comment]
Try with https://github.com/strawberrymusicplayer/strawberry/commit/204508478f36e17bea6612edf96a4a619bda52ba
It should fix cancelling logout if Strawberry is already minimized in tray, then it will exit now.

**Comment by alekksander** [comment]
just experienced it again while trying to „log out” my session
