### ISSUE TITLE
Tidal no Masters 

### ISSUE THREAD

**Issue by olo81** [jonaski/strawberry#285]
Music in high technology is not used, its parameters are reduced to the use of 16bit

the problem appears on ubuntu, I don't know how it is on other systems

![Zrzut ekranu z 2019-10-28 18-57-23](https://user-images.githubusercontent.com/8314359/67704206-f61c7380-f9b4-11e9-85f9-a7352f1a159c.png)
![Zrzut ekranu z 2019-10-28 18-57-34](https://user-images.githubusercontent.com/8314359/67704217-fae12780-f9b4-11e9-93f2-d5e488e355a9.png)

**Comment by jonaski** [comment]
It will only work with FLAC, because Tidal Masters uses a proprietary format (MQA), we can't support it. Also, the Tidal support in Strawberry is not official, so we don't have any API documentation or official access to the API. I've updated the README to reflect it. The alternative is to remove Tidal support entirely. Tidal won't give us official access, I've asked.
https://github.com/jonaski/strawberry/commit/76c6f7e733b7228bd719ad203b26a3fe9634f118

**Comment by RomanHargrave** [comment]
@jonaski while I personally don't put much stock in to things such as MQA, I don't believe Strawberry needs to do anything special to support it. When you request MQA data from TIDAL, you will get a listenable FLAC file that has additional data encoded outside of audible range that is decoded by specialised hardware.

**Comment by jonaski** [comment]
We already have the HI_RES option in the setting. I don't think it works though. Even though it probably can be decoded like a FLAC, it's sent differently, and I don't think gstreamer would recognize the stream. In that case we would need to write a gstreamer plugin for it, I'm not really interested in doing that, since it's a lossy and closed format.
I have no API documentation, no information about MQA, and I don't even have a subscription to Tidal now, so not worth the time.
But if anyone else want to fix it, their welcome.
There is some info on reddit here:
https://www.reddit.com/r/audiophile/comments/8itd0z/mqa_vs_plain_old_flac/

**Comment by RomanHargrave** [comment]
> Even though it probably can be decoded like a FLAC, it's sent differently

What API key were you using?
