### ISSUE TITLE
Error handling multiple albums with same name

### ISSUE THREAD

**Issue by tobox** [jonaski/strawberry#288]
**Describe the bug**

I found an annoying behavior in clementine, which made me switch to strawberry. But the bug seems to be present in strawberry as well. Suppost I have artists "A" and "B" with album "Best of":

```
./A
./A/01.mp3
./A/02.mp3
./B
./B/01.mp3
./B/02.mp3
```
Then they are correctly scanned and inserted into the database. But if I change the artist of one of the files in B to B_X, **both** albums are moved to "Various Artists". This behaviour is very difficult to debug once there are many albums involved, because it is difficult to determine which album caused the trouble.

**System Information:**
Debian buster
Strawberry 0.6.5

Correct:
![Strawberry_Correct](https://user-images.githubusercontent.com/4719666/67961941-b34cdc80-fbfc-11e9-8fd6-c5d8c29ecd96.png)

Incorrect:
![Various_Artist](https://user-images.githubusercontent.com/4719666/67961939-b34cdc80-fbfc-11e9-8849-df3eb453c1e4.png)

Expected: 
A remains under "A", B moves to "Various Artists". For small examples, the erratic behaviour disappears if AlbumArtist is set correctly for "B", but it does not work for my larger, real world examples.

**Comment by jonaski** [comment]
I had a quick look at the source code, and what your experiencing makes sense because it calculates compilations based on album title only.  If more there are more artists than directories, it will consider them compilation, in and your case it will be of course.
The code is here: https://github.com/jonaski/strawberry/blob/master/src/collection/collectionbackend.cpp#L891
I really don't understand why it was written like this. I don't understand why they didn't just base the logic on directories instead, or directory + album, then calculate how many artists there are per directory.
I finally had time to test it in practice now too, the reason I've never seen this before is probably because I don't have many albums with the same titles, and it will only happen if one of the albums is a compilation without album artist. But it's still a bug.

**Comment by jonaski** [comment]
I've spent a few hours on this. It should be fixed now. There was a different bug there too caused by mixing bool/ints so albums got stuck in "compilation detected" mode, preventing them from going out of the "Various artists" when artist was updated.

**Comment by tobox** [comment]
Thank you so much for fixing it, especially so quickly! Good work - will recommend Strawberry :-)
