### ISSUE TITLE
Various Artists handleing borken in 6.5>6.6 update

### ISSUE THREAD

**Issue by Sal1950** [jonaski/strawberry#312]
**Describe the bug**
Albums with songs by Various Artists in 6.5 and older versions would create a menu entry at the very top under a "Various" entry that listed that albums name and open to a submenu of the tracks, listing songs name and maybe the individual artist. (Like a normal album listing)
Since the update to 6.6, after a full collection rescan, that album listing has disappeared and each individual song is scattered across the menu by artist name.

**To Reproduce**
Install a compilation album such as 2008 Cadillac Records Soundtrack or 2002 The Legendary Story Of Sun Records

**Expected behavior**
Same behavior as we had in 6.5 and earlier.  Also the default behavior by Clementine only the menu is created alphabetically under Various Artists

**Screenshots:**
Will edit with screenshots

**System Information:**
 - Operating system:  PCLinuxOS
 - Strawberry Version: 6.6

**Additional context**

**Comment by jonaski** [comment]
I changed the detecting of compilations to work on directory + album instead of just the album title alone.
Because otherwise albums by two different artists that have the same album title can go into the various artists, and that's not what we want.
It will go into the various artists only if the directory where the songs are have the same album title and multiple artists (either different artist or different album artists depending on the grouping).
It works fine here with all different combinations I can think of.
So could you share some more details about directories, file format, tags, etc.

**Comment by Sal1950** [comment]
Two Screenshots
Screenshot6-5 shows the Various Artists entry at top of menu and alblum enterd in it.
Screenahot6-6 shows the Various Artists gone and four songs by Byonce now listed individually.
I have like 15 albums that used to be nicely listed in Various that have now turned into 150-200 extra individual entries.  Kind of make a real mess of the menus!
What other type of info would you like and from which Version #

![Strawberry6-5](https://user-images.githubusercontent.com/16216512/69377254-e7567300-0c79-11ea-9a63-b176cb031206.png)
![Strawberry6-6](https://user-images.githubusercontent.com/16216512/69377358-179e1180-0c7a-11ea-929d-8165043e3289.png)

**Comment by Sal1950** [comment]
Hope this helps
![Summary](https://user-images.githubusercontent.com/16216512/69378151-cb53d100-0c7b-11ea-87ba-56e5f84b501d.png)
![tags](https://user-images.githubusercontent.com/16216512/69378166-d1e24880-0c7b-11ea-957e-c9879d06dfd7.png)

**Comment by jonaski** [comment]
I see what the problem is. The problem only occurs when there are spaces in the filename/path of the song.
I fact, I have already fixed it in commit https://github.com/jonaski/strawberry/commit/175e568a28944e5a0f527f4187c54f3a26c26fdc and https://github.com/jonaski/strawberry/commit/c4f7054ca6263886cd8a7f6c992d37a8cd452872
But that was just after the release of 0.6.6.
I can make a new release next week.

**Comment by jonaski** [comment]
The reason I didn't see that immediately is because I have underscores instead of spaces on all my song filenames and paths.

**Comment by Sal1950** [comment]
OK, thanks very much for all your work here.
I'll be looking forward to the fix.

**Comment by Sal1950** [comment]
Received the 0.6.7 update from the PCLinuxOS repository today. That cured all my issues with the Various Artists handling. Thanks a ton Jonas! 
Best Holiday Wishes to you and yours.
Sal

**Comment by jonaski** [comment]
Glad to hear. Best holiday wishes to you too.
