### ISSUE TITLE
Add automatic scoring or mention it in the readme if added already

### ISSUE THREAD

**Issue by matkoniecz** [jonaski/strawberry#317]
**Is your feature request related to a problem? Please describe.**
I have a collection of music, some liked more, some liked less - what is changing over time. I want to play my favorite songs more often. Manual managing this is not a good use of a time.

**Describe the solution you'd like**
In Clementine it is really to find my favorite music by simply sorting by an automatic score (increased when substantial part of the song is played, decreased when skipped)

**Describe alternatives you've considered**
Manual scoring - sadly this takes far more time and upkeep. I manually scored all my collection in Clementine, but I anyway use primarily sorting by an automatic score.

Simply using Clementine is not feasible as this project is dying (no release since 2016, not installable on Ubuntu 18.04.

**Additional context**
Should be possible to cherry pick it from Clementine - based on https://github.com/clementine-player/Clementine/issues/6325 it is not present in Strawberry because for some reason it was forked from an outdated version

**Comment by jonaski** [comment]
Unless more contributors join this isn't likely to be done. I don't have time to work on it as much as I have done for the past years (unless I quit my day job). I will mostly stick to maintaining the features we got, and address bugs and updates.
I'm not too keen on the auto score system either.
We will most likely add back manual ratings and smart playlists since those are the 2 most requested features that were present in Clementine. But right now there are issues with that too.
Strawberry isn't based on an outdated version, don't believe everything you read.
It's based on a modified version of Clementine I started on years ago, but it has been merged with Clementine since.
The reason some features aren't there is because I ported it to Qt5 before there was a qt5 branch in Clementine, I stripped off some features that I didn't use or want to make it easier to maintain, and also because I reorganized the db schema. Specifically the internet services needed the most work to be updated to qt 5. I ended up abandoning the whole thing before it was finished because it ended up taking too much time, didn't pick it up before many years later. That's what the description in the readme refers to.

**Comment by matkoniecz** [comment]
Closing per

> I'm not too keen on the auto score system either.

**Comment by JulianVolodia** [comment]
> Strawberry isn't based on an outdated version, don't believe everything you read.
> It's based on a modified version of Clementine I started on years ago, but it has been merged with Clementine since.

Hi @jonaski, not exactly know what you say. Does it mean something about the Strawberry life? Still will be maintain, merged and/or abadoned?

Kind regards.
