### ISSUE TITLE
[Request]: A possibility to change GUI font size.

### ISSUE THREAD

**Issue by tnilzon** [jonaski/strawberry#349]
Hi, great app!
Just trying it with TIDAL. Seem to be a "must have" if you would like to benefit the HI-Res quality offered by TIDAL premium account.

Now, for the request: I would like to see an option in the settings to be able to change the font size (mainly the playlist font size). I am using Strawberry with TIDAL on my TV-screen, and it is hard to read from the couch. The "best" solution would be if all parts of the GUI could have customization for the fonts (for the use on TV-screen).

Thank's !

**Comment by jonaski** [comment]
TIDAL hi-res isn't possible, since we can't get official support for an open source project from Tidal.
For the font thing there already is issue: https://github.com/jonaski/strawberry/issues/303
There are also other issues for making the UI more optimized for higher resolutions:
https://github.com/jonaski/strawberry/issues/250
https://github.com/jonaski/strawberry/issues/299

**Comment by tnilzon** [comment]
Hi, ok. Sorry to learn about the TIDAL HI-Res not possible.
But, anyway. Strawberry seem to be a very nice music player/streamer experience for me (haven't heard about it until I searched for a Linux TIDAL desktop client.

Just a question: With the present state of Strawberry, what is the highest quality possible when streaming from TIDAL?

**Comment by jonaski** [comment]
When I had a subscription I was always using the "Lossless" setting which worked very well, you get standard 44.1/16 CD quality streaming, it's lossless, which in my opinion is the most important. The MQA isn't possible, that's probably the hi-res setting.
There is no guarantee how long it will work though, Tidal might change the API at any time, we don't have an agreement with them or any partner status.
