### ISSUE TITLE
LMS: Parameter 'id': bad format (0)

### ISSUE THREAD

**Issue by glesik** [jonaski/strawberry#354]
Strawberry produces an error "Parameter 'id': bad format (0)" when trying to sync collection with [LMS](https://github.com/epoupon/lms) via Subsonic API.

**To Reproduce**
1. Enter server address and credentials in Strawberry settings.
2. Click Test button and receive "Test successful" message.
3. Click Refresh catalogue and receive the error.

**Expected behavior**
Collection syncs successfully.

**System Information:**
Raspbian 10, LMS 3.2.0, Strawberry 0.6.8.

**Additional context**
It seems that Strawberry expects `id`, `artistId`, `albumId` to be a number while according to e. g. [Subsonic REST API 1.16.1](http://www.subsonic.org/pages/inc/api/schema/subsonic-rest-api-1.16.1.xsd) it is a string. LMS appends character prefix to the `id`s and I suspect that is the reason of the error. Clementine [seems](https://github.com/clementine-player/Clementine/blob/master/src/internet/subsonic/subsonicservice.cpp#L536) to handle those fields as a string and syncs the database fine.
I believe Strawberry is the right place to fix this issue because of the Subsonic API specs.

**Comment by epoupon** [comment]
You can test this using the LMS demo instance: (https://lms.demo.poupon.io), using demo/demo as login/password

**Comment by jonaski** [comment]
The problem is that we use integers internally to store song and artist id, which is also stored as integers in the DB. This was implemented for TIdal before we had Subsonic or Qobuz support, Tidal uses integers for all of them in the API. When I added Qobuz, it was using string for album id, but integers for both artist and song id, so I had to convert all the song tables album id's to strings. That's why album id is string, but artist and song ids are still integers.
I've fixed the Subsonic support now to keep album id as string and not convert it to integers, so now you can fetch all the albums successfully. However song id is still integers so when LMS use characters in the song id its converted to 0, so no song will play.
SQLite does not allow adding and removing columns so it require to recreate the whole tables and convert existing data into the new tables.
So a full fix require a lot more work and complete conversion of all the song tables, because all song tables must be identical.

**Comment by jonaski** [comment]
Our Subsonic support don't use any code from Clementine, we use JSON while Clementine uses XML.
I had a brief look at how Clementine does it, it actually stores the song id as a query item on the url instead of storing the song id separately, and it just appends the login stuff to the URL in the URL handler. It's possible to do that too, because we don't need the song id for anything else.

**Comment by jonaski** [comment]
I just realized that it prefixes all song ids with "tr-", so I can just strip that off.

**Comment by glesik** [comment]
That would be a great simple solution for this particular case. I understand that changing database scheme is a big deal, but maybe someday it will be needed anyway. Meanwhile we can hope no server developer decides to use, say, UUIDs for this purpose. ;)

**Comment by jonaski** [comment]
I just saw that I actually use the url path to store the song id, so this wasn't as difficult to fix as I thought. The song id in the DB isn't actually used for anything for subsonic so this fix is perfectly fine. I will still set the song id with the stripped off "tr-" to make it unique for each song.
It should be fixed now. I'm testing with the demo one and it's working.

**Comment by epoupon** [comment]
This fix seems does not seem very robust (as you said, a server implemtation may store whatever it needs, like musicbrainz's UUID), but that's up to you of course.
By the way, do you manage to fetch covers with this fix?

**Comment by jonaski** [comment]
Its robust for subsonic because I don't actually use the song id for anything, I store the real song/track id returned by the API in the path of the url. I'll change the artist and song id to strings if I implement a new service that requires it, it's easier to to it then since we need a schema update anyway.
I've fully fixed the covers too.

**Comment by epoupon** [comment]
Ok great! Thanks for fixing it!
