### ISSUE TITLE
album artwork

### ISSUE THREAD

**Issue by alekksander** [jonaski/strawberry#43]
cover thumbnails are not displayed if image is in directory inside the album directory. 
•walk around for that would be a rule to look for given file names inside any existing sub–directory. it could also ignore other words in the filename if given rule as asterisk (`*front*,*cover*` – etc). 
•another walk around is to put automatically downloaded cover (one that's generated in low corner) as invisible in listened album, instead of somewhere in the system.
 if i may add for me personally the first solution seems more reasonable as it doesn't create additional files/mess in ones collection.

![image](https://user-images.githubusercontent.com/3148302/50695834-1fdb6700-103e-11e9-8682-47326531fce3.png)

**Comment by jonaski** [comment]
The discovery of album covers is done by the collection watcher at the same time as the directories are scanned. I've thought about your suggestion, it's not as easy as it may sound, it's actually quite tricky to do unfortunately, there is a hash map used for the directories that will use the directory as the key and the images as the values. Using images in subdirs too will involve a lot extra checks, logic and possible loops, it's not worth the hassle and will make the scanner slower. Also you have to take into consideration that there might be other audio files in subdirs to. Some people put their whole home dir as a music directory, etc.
If I understand your second suggestion correctly, you mean that it should save the image in the album directory instead of ~ /.local/share/strawberry/strawberry/albumcovers/ . I've actually thought about that myself, should be easy to implement. We could have an option for that in the settings.

**Comment by alekksander** [comment]
thank You for Your interest and explanation. Your understanding of my second suggestion is correct. willing to test once You have time to work on it.

**Comment by jonaski** [comment]
The best site for albums covers is https://www.albumartexchange.com/
All the covers there are superior to any other site.
However there isn't any API anymore (they had before), I think the reason was that they can't use advertising with that, and it requires too much bandwidth.

**Comment by jonaski** [comment]
You can try this now:
https://github.com/jonaski/strawberry/commit/2211716d0403ac8ab97b42756fe7607379634c68

**Comment by jonaski** [comment]
The settings are in "Collection":
![image](https://user-images.githubusercontent.com/10343810/54161563-da2e8680-4452-11e9-8cb0-d373802af386.png)

**Comment by alekksander** [comment]
„save **automatically downloaded** album covers in album directory”?
otherwise – wow – thank You!
