### ISSUE TITLE
Custom color set causes freeze

### ISSUE THREAD

**Issue by alekksander** [jonaski/strawberry#50]
Both issues address settings from Appearances:

•Selecting „Use custom color set” freezes strawberry instantly. this is repetitive and happens every time i select it. even animation from radio button is not finishing. there is no output from systems console to track down the issue. any other way to hunt–down the reason?

•Custom image as background is not respected – it displays tiled strawberries instead. same behavior occurs if „No background image” is selected. additionally as can be noticed on the picture below, path to chosen png is greyed-out each time application restarts.

![image](https://user-images.githubusercontent.com/3148302/50913471-b8a22600-1434-11e9-9e25-0a94968203bb.png)

**Comment by alekksander** [comment]
custom color set still freezing app. is it system related issue rather than strawberry?

**Comment by jonaski** [comment]
I tested it yesterday and it worked fine, but today I get the freeze on my primary machine, it as Qt 5.12.0
I have done significant test and debugging on the appearance settings, because there was a crash when changing the color set, it happened in the Qt function setStyleSheet() and I found no explanation.
I did a workaround, I added widget->setStyleSheet(""), before setting the new styresheet in two places, I even tested on several distros and different desktops, the crash was completely gone.
https://github.com/jonaski/strawberry/blob/master/src/core/mainwindow.cpp#L876
https://github.com/jonaski/strawberry/blob/master/src/core/stylesheetloader.cpp#L96
But looks like this now leads to a loop with Qt 5.12.0 which causes a freeze.
I got another machine with Q 5.9 and there it works fine.

**Comment by jonaski** [comment]
Try this fix 5746ee7

**Comment by alekksander** [comment]
works. thank You

**Comment by alekksander** [comment]
another related minor issue – if custom color is set, i'm unable to use seekbar.
