### ISSUE TITLE
[FEATURE] Buffering visual indicator in play bar

### ISSUE THREAD

**Issue by rijnhard** [jonaski/strawberry#54]
It appears as if it's only buffering some short unknown amount of time and then waits until I hit the end of the buffer before it buffers again. It's a pretty brutal listening experience.

The buffering should continue while paused. and it should aim to keep X seconds buffered always regardless of play state. It would be nice if this was configurable and had a default of 30sec (personal preference).

Another bonus would be if we had an underlying shadow on the song progress bar that showed how far we have buffered (like youtube videos).

**Comment by rijnhard** [comment]
wait. now my experience is much better after leaving it paused for a while. It may be my internet but I can't tell since the amount of buffer isn't visually visible.

**Comment by rijnhard** [comment]
Aaaand Tidal is brutal again. And Pausing seems to have no notable effect on buffer. Apologies, but my results are inconsistent

**Comment by jonaski** [comment]
I don't really want a graphical progress indicator. Also it would require to modifying the main window GUI and change a lot of things with it.
I've tested Tidal over 3- months after implementing it, buffering takes less than 3 seconds, and I don't see any issues.
I got a poor internet connection, basically I got a large antenna on the wall of my house, and the internet is received through radio. But it works, but I can't download or stream on another computer at the same time.
I think the real issue here is your internet connection.
The actual buffering is done by the engine, gstreamer will work best for streaming. I don't think much can be improved anyway.
The actual issue is gap less playback, see #26.
