### ISSUE TITLE
Last.fm problem signing in

### ISSUE THREAD

**Issue by hype3** [jonaski/strawberry#57]
Testing Strawberry 0.5.1 on a work computer running Windows 10 and Firefox 64.0.2
When I click on login button in settings for Last.fm a dialog opens and I choose open then i get to last.fm page. Clicking on Yes, allow access button. I get a website with the following error:

Secure Connection Failed

The connection to localhost:62952 was interrupted while the page was loading.

The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
Please contact the website owners to inform them of this problem.

**Comment by alekksander** [comment]
try another browser

**Comment by hype3** [comment]
Ok so here is my test results:

**Comment by hype3** [comment]
Ok so here is my test results:
Firefox - Not working
Google Chrome - Works
Internet Explorer - Not working
Microsoft Edge - Not working
Opera - Works
Vivaldi - Works

**Comment by alekksander** [comment]
seems like blink backend is the only one compatible with this. 

this comment states about this behavior:
https://github.com/jonaski/strawberry/issues/13#issuecomment-449657893

**Comment by jonaski** [comment]
I think it's because Firefox don't allow a https site to forward to a http, so it changes the url scheme to https, but the built-in webserver in Strawberry that receives the token isn't https, so it sends a plain text response, which firefox thinks is a broken certificate. If there isn't a setting in Firefox that can change that, then I'm afraid the only thing I could to is to write the built in webserver to use https instead, but that will still be an issue, because that means that people will get certificate errors, otherwise it has to create a valid certificate for localhost  on the fly (is that even possible?), but I'm not sure web browsers will even except such a certificate with localhost as domain anyway.
So I don't see any easy solution to this except to use another browser, or find out if there is a setting to prevent firefox to translate to https.

**Comment by hype3** [comment]
No problem on Linux with Firefox and doing the same thing works fine.

**Comment by jonaski** [comment]
Not for me, maybe related to a version, or a setting perhaps?
I use version 64.0 Build ID: 20181206201918

**Comment by Fef0** [comment]
Hi @jonaski, even though this issue is closed I'm having the same issue with Arch Linux and Firefox 66.0.3 (64bit). 
Once I have clicked the login button and allowed the access from the last.fm page, it just redirects me to an error page.
Any idea of a possible solution or a temporary workaround?

**This is the Firefox message:**
```
An error occurred during a connection to localhost:42127. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG

- The

 page you are trying to view cannot be shown because the authenticity of the received data could not be verified.

- Please

 contact the website owners to inform them of this problem.
```

**Comment by jonaski** [comment]
Not other than using another web browser like chrome.
I tried to change settings in firefox to make it work, but was unable to, but it's probably a setting that could make it work.

**Comment by Fef0** [comment]
@jonaski Clementine plugin for last.fm actually works, did you try to just use it?

**Comment by jonaski** [comment]
What plugin is that?

**Comment by Fef0** [comment]
@jonaski here's the link of the module: https://github.com/clementine-player/Clementine/tree/master/src/internet/lastfm

**Comment by jonaski** [comment]
Thats the same OAuth method I use, unless you mean the older android method in 1.3.1 and previous.

**Comment by Fef0** [comment]
But that's pretty weird, because that actually works with Firefox, no problem whatsoever.
Did you use the same code or just the same method?

**Comment by jonaski** [comment]
I'm not using the same code, but the same method.
But interestingly I tested both the Qt 4 version of Clementine and the Qt 5 version now, the Qt 5 version does not work, but the Qt 4 version works.

**Comment by Fef0** [comment]
@jonaski oh, you're right, I have the same issue with Qt5... Do you think that it could be related to the different version? What did they change from Qt4 to Qt5 about OAuth?

**Comment by jonaski** [comment]
I tried to compare and see if there is any logical reason. But it suddenly stopped working for me with the Qt 4 version also.

**Comment by Fef0** [comment]
@jonaski I can't really replicate this issue, with Clementine 1.3.1 everything works flawlessly (it uses Qt 4.8.7 if this helps)

**Comment by jonaski** [comment]
I've added a workaround to use https instead for the redirect server (localhost), the disadvantage is you need to accept self-signed security certificate for localhost.

**Comment by Fef0** [comment]
@jonaski Perfect, everything works now! Thank you very much!
