### ISSUE TITLE
Make dmg package for macOS

### ISSUE THREAD

**Issue by jonaski** [jonaski/strawberry#7]

**Comment by thenewnano** [comment]
I have kind of had to compile Clementine for MacOS these days as I was trying to figure out a bug there, they have a docker image that you should be able to just use to cross compile. I didn't look further into it, but data changes in the container are not persistent, mounting a volume om docker run should be a better option and buildbot should be able to work in docker as well, so the way to go for compiling locally  is a docker image with all dependencies installed, or just install them all to your  build slave and you will be fine .  
Now I have to compile strawberry to see if it behaves better on Mac than Clementine.

**Comment by thenewnano** [comment]
@jonaski  the dmg is something good tohave, you should be bale to copy the recipe from Clementine. But if you upload a ZIP file including the application folder that would do for many of us. 

I now give up compiling now after more than two hours, I tried using the cross compiler docker  from Clementine but it doesn't have QT5 , doing it native on my Mac also goes 100% then fails due to link error after build for chromaprint ... it is installed Cmake has already found it as well... 
so I don't get it 
`ld: library not found for -lchromaprint
`

**Comment by jonaski** [comment]
Just do: export LIBRARY_PATH=/usr/local/lib

**Comment by jonaski** [comment]
I'm making development builds for macOS through Travis-CI now, it's automatically creating the dmg.
https://github.com/jonaski/strawberry/releases
You can test it and report back any problems. But I won't be making regular releases since I don't even have a mac.

**Comment by jonaski** [comment]
Moving the builds for macOS to upload on https://builds.strawbs.net/macos/
