### ISSUE TITLE
Next/Previous track icons should have a vertical line at arrow tip

### ISSUE THREAD

**Issue by sylvainsab** [jonaski/strawberry#76]
Next Track and Previous Track icons usually have a vertical line at the tip of the outward-pointing arrow, to differentiate them from the Fast Forward and Fast Reward.

The image as I see it being that you "push" the whole of the content at once rather than simply increase the speed of going through it.

**Comment by jonaski** [comment]
I know, but the icon set I picked did not have those icons, I decided to use the forward / rewind instead because I liked these icons, didn't really bother me too much.
I did this in 2012 when I started to modify Clementine, so I don't remember where I got them. I picked these because I wanted icons that matched the colors of the analyzer and the volume control similar to what Amarok 1.x had.
So the only solution to this is to use another media icon set, and I can't really find any that I want to use, so that means creating a new, which is probably the best anyway so the it has a unique look.
I don't know how to make vector graphics or how to use inkscape so this will probably not be done unless someone else creates it, and it is hard to find anyone with the skills that does anything for free.
