### ISSUE TITLE
[Feature Request] Port to OSX 10.11+

### ISSUE THREAD

**Issue by rodneyrod** [jonaski/strawberry#79]
Not sure if there's any specific stuff to High Sierra that's been added, but if there hasn't, it might be better for maximum compatibility to drop the version requirements for the daily builds, El Capitan is the last supported version of OSX that supports some hardware.

**Comment by jonaski** [comment]
What version requirement? Not sure what you mean.
The macos builds are built on high sierra because thats what travis-ci got.

**Comment by rodneyrod** [comment]
I'm only sure about it in XCode, but you can select the minimum version of OSX supported by the .app

For the nightlies currently, they're 10.13+
Just wondering if there's anyway to compile this for 10.11+ instead?

**Comment by jonaski** [comment]
I think it should work.
Most of the macos specific code is not updated.
I don't know about xcode, I use cmake, https://github.com/jonaski/strawberry/wiki/Compile-and-install-on-macOS

**Comment by rodneyrod** [comment]
I'm not sure with CMake, I mostly use XCode or Homebrew scripts, but I think this flag might be how to set it?
https://cmake.org/cmake/help/v3.11/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html

**Comment by jonaski** [comment]
Yes, probably.
I'm not a macos programmer,and I don't have a mac, and I don't really have the time to maintain the macos specific code in addition to the rest of the work. That's why I don't make releases for macos either, but I've assured it compiles on macos and kept the macos specifics there, so it should be pretty easy for someone familiar with macos programming to fix the remaining stuff necessary and a few compile warnings.
I'll accept a PR that adds that that flag for macos so it could be backward compatible, if you or someone else want to work on it.
