### ISSUE TITLE
Invalid URI error when playing from SMB share (windows)

### ISSUE THREAD

**Issue by ccoenen** [jonaski/strawberry#83]
I keep my music on a NAS which I access via SMB from a windows machine. I can play music with clementine 1.3.1 from that same location just fine. 

I can add that directory to my library in Strawberry 0.5.2-45-gdc04961, and it scans all files as expected. I can't play any of them though. Playback yields this error (path blurred out, but it's essentially `//nas-name/Sharename/path/filename.mp3` which is not an unexpected thing). The forward slashes shouldn't be a problem on recent versions of windows (i can view that file in `cmd.exe` just fine when I specify it exactly that way).

![playback error](https://user-images.githubusercontent.com/124909/53277987-0504a500-3707-11e9-979e-38de1062ecb8.png)

Here's clementine side by side with strawberry with that file's metadata:

![metadata panel](https://user-images.githubusercontent.com/124909/53277976-f74f1f80-3706-11e9-9c22-f76f6213703e.png)

**Comment by ccoenen** [comment]
Another tiny bit of information: the playlist has this "source" icon, and for all smb files this is a black record. For local files, it's a blue folder:

![source icons](https://user-images.githubusercontent.com/124909/53278076-6298f180-3707-11e9-9711-2bdd3b5ecf80.png)

I can play the same file from the local disk just fine.

**Comment by jonaski** [comment]
The engine code is completely changed from Clementine, so the issue may be in the engine code.

If someone wants to look into this before I get the time:
Maybe gstreamer does not like the // conversion I do.
The conversion is done here: https://github.com/jonaski/strawberry/blob/master/src/engine/gstengine.cpp#L732
Also, a difference from Clementine is that I use playbin instead of uridecodebin.

The QUrl class is changed in Qt 5, so it does not accept the URL's that gstreamer wants, so I'm doing a conversion from QUrl to a QByteArray early when loading the URL, but I keep the original QUrl so it can be traced back.

As for the different icons.
The vinyl shows if the song is part of your collection. But it shows the folder icon if the song is added to the playlist from the file view or dragged.

**Comment by ccoenen** [comment]
>  The vinyl shows if the song is part of your collection. But it shows the folder icon if the song is added to the playlist from the file view or dragged.

Ah :-) got it!

**Comment by jonaski** [comment]
The problem was of course that file:// was missing in front of the converted UNC path "//host/path".
Fixed now in https://github.com/jonaski/strawberry/commit/384209ba70d9f1802d5c50c15cdb13fb9f13acf7

**Comment by ccoenen** [comment]
wow _that_ was quick! Thank you for fixing this so quickly. I've downloaded the build and I can confirm that the problem is gone! 👍

**Comment by jonaski** [comment]
I found out that the source was reset to file (folder icon), even when the song was in the collection after editing tags, possible some other scenarios too. Fixed it now.
If anyone has that problem they can set the songs source back to collection with this:

```
sqlite3 ~/.local/share/strawberry/strawberry/strawberry.db
update songs set source = 2;

```

**Comment by ccoenen** [comment]
will give it a rescan :-)
